FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o order_server ./entry/order_server

FROM gcr.io/distroless/static

COPY --from=builder /app/order_server /order_server

USER nonroot:nonroot

ENTRYPOINT ["/order_server"]