FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o auth_server ./entry/auth_server

FROM gcr.io/distroless/static

COPY --from=builder /app/auth_server /auth_server

USER nonroot:nonroot

ENTRYPOINT ["/auth_server"]