FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o order_gateway ./gateway/order

FROM gcr.io/distroless/static

COPY --from=builder /app/order_gateway /order_gateway

USER nonroot:nonroot

ENTRYPOINT ["/order_gateway"]