FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o auth_gateway ./gateway/auth

FROM gcr.io/distroless/static

COPY --from=builder /app/auth_gateway /auth_gateway

USER nonroot:nonroot

ENTRYPOINT ["/auth_gateway"]