FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o courier_server ./entry/courier_server

FROM gcr.io/distroless/static

COPY --from=builder /app/courier_server /courier_server

USER nonroot:nonroot

ENTRYPOINT ["/courier_server"]