FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o delivery_server ./entry/delivery_server

FROM gcr.io/distroless/static

COPY --from=builder /app/delivery_server /delivery_server

USER nonroot:nonroot

ENTRYPOINT ["/delivery_server"]